# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myclient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Email')),
                ('hide', models.CharField(blank=True, choices=[('no', 'Не скрыт'), ('yes', 'Скрыт')], default='0', max_length=30, verbose_name='Скрыт')),
                ('hide_date', models.DateField(blank=True, null=True, verbose_name='Скрыть до')),
                ('area_ot', models.IntegerField(blank=True, default=0, verbose_name='Площадь от')),
                ('area_do', models.IntegerField(blank=True, default=0, verbose_name='Площадь до')),
                ('price_obsh', models.IntegerField(blank=True, default=0, verbose_name='Цена до')),
                ('price_m', models.IntegerField(blank=True, default=0, verbose_name='Цена до за м2')),
                ('dop_kont', models.TextField(blank=True, max_length=1000, verbose_name='Дополнительные контакты')),
                ('metro', models.BooleanField(max_length=30, verbose_name='У метро')),
                ('adres', models.BooleanField(max_length=100, verbose_name='С адресом')),
                ('komisiya', models.BooleanField(max_length=30, verbose_name='Без комиссии')),
                ('etaj', models.BooleanField(max_length=30, verbose_name='1 этаж')),
                ('podborka', models.BooleanField(max_length=30, verbose_name='Отправить подборку')),
                ('type_obj', models.CharField(blank=True, choices=[('undeg', 'Подземка'), ('street', 'Улица'), ('tc', 'Отдел\\ТЦ')], default='undeg', max_length=30, verbose_name='Тип объекта')),
                ('my_manager', models.ForeignKey(on_delete=models.SET(myclient.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hide'],
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Клиент',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Naznach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Продукты', 'Продукты'), ('Общепит', 'Общепит'), ('Другое', 'Другое')], default='F', max_length=30, verbose_name='Группа')),
                ('options', models.CharField(max_length=100, verbose_name='Назначения')),
            ],
            options={
                'verbose_name_plural': 'Назначения',
                'verbose_name': 'Назначение',
                'db_table': 'naznach',
            },
        ),
        migrations.CreateModel(
            name='Okrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=100, verbose_name='Округ')),
            ],
            options={
                'verbose_name_plural': 'Округа',
                'verbose_name': 'Округ',
                'db_table': 'okrug',
            },
        ),
        migrations.CreateModel(
            name='Prioritet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritet', models.CharField(max_length=30, verbose_name='Приоритет')),
                ('num', models.IntegerField(default=1, verbose_name='Важность')),
            ],
            options={
                'ordering': ['-num'],
                'verbose_name_plural': 'Приоритеты',
                'verbose_name': 'Приоритет',
                'db_table': 'prioritet',
            },
        ),
        migrations.CreateModel(
            name='TaskClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('task', models.TextField(verbose_name='Задача')),
                ('end', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.Client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prioritet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.Prioritet', verbose_name='Приоритет')),
            ],
            options={
                'ordering': ['-prioritet'],
                'verbose_name_plural': 'Задачи клиента',
                'verbose_name': 'Задача клиента',
                'db_table': 'task_client',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='naznach_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naznach_one', to='myclient.Naznach', verbose_name='Назначение №1'),
        ),
        migrations.AddField(
            model_name='client',
            name='naznach_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.Naznach', verbose_name='Назначение №2'),
        ),
        migrations.AddField(
            model_name='client',
            name='okrug',
            field=models.ManyToManyField(blank=True, to='myclient.Okrug', verbose_name='Округ'),
        ),
    ]
