# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='Email')),
                ('hide', models.CharField(blank=True, choices=[('no', 'Не скрыт'), ('yes', 'Скрыт')], default='', max_length=30, verbose_name='Скрыт')),
                ('area_ot', models.IntegerField(blank=True, default=0, verbose_name='Площадь от')),
                ('area_do', models.IntegerField(blank=True, default=0, verbose_name='Площадь до')),
                ('price_obsh', models.IntegerField(blank=True, default=0, verbose_name='Цена до')),
                ('price_m', models.IntegerField(blank=True, default=0, verbose_name='Цена до за м2')),
                ('dop_kont', models.TextField(blank=True, max_length=1000, verbose_name='Дополнительные контакты')),
                ('metro', models.BooleanField(max_length=30, verbose_name='У метро')),
                ('adres', models.BooleanField(max_length=100, verbose_name='С адресом')),
                ('komisiya', models.BooleanField(max_length=30, verbose_name='Без комиссии')),
                ('etaj', models.BooleanField(max_length=30, verbose_name='1 этаж')),
                ('podborka', models.BooleanField(max_length=30, verbose_name='Отправить подборку')),
                ('okrug', models.CharField(choices=[(1, 'Центр'), (2, 'Север'), (3, 'Юг'), (4, 'Восток'), (5, 'Запад'), (6, 'Область')], default='F', max_length=30, verbose_name='Округ')),
                ('type_obj', models.CharField(choices=[('undeg', 'Подземка'), ('street', 'Улица'), ('tc', 'Отдел\\ТЦ')], default='F', max_length=30, verbose_name='Тип объекта')),
                ('my_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'db_table': 'client',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Naznach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Продукты', 'Продукты'), ('Общепит', 'Общепит'), ('Другое', 'Другое')], default='F', max_length=30, verbose_name='Группа')),
                ('options', models.CharField(max_length=100, verbose_name='Назначения')),
            ],
            options={
                'verbose_name': 'Назначение',
                'db_table': 'naznach',
                'verbose_name_plural': 'Назначения',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='naznach_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naznach_one', to='myclient.Naznach', verbose_name='Назначение №1'),
        ),
        migrations.AddField(
            model_name='client',
            name='naznach_two',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myclient.Naznach', verbose_name='Назначение №2'),
        ),
    ]
