# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='okrug',
            field=models.CharField(blank=True, choices=[(1, 'Центр'), (2, 'Север'), (3, 'Юг'), (4, 'Восток'), (5, 'Запад'), (6, 'Область')], default='', max_length=30, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_obj',
            field=models.CharField(blank=True, choices=[('undeg', 'Подземка'), ('street', 'Улица'), ('tc', 'Отдел\\ТЦ')], default='F', max_length=30, verbose_name='Тип объекта'),
        ),
    ]
