# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='myclient.Client', verbose_name='Клиент'),
        ),
    ]
