# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0002_auto_20170514_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskclient',
            name='end',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
