# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0004_auto_20170504_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='okrug',
            field=models.CharField(blank=True, choices=[('1', 'Центр'), ('2', 'Север'), ('3', 'Юг'), ('4', 'Восток'), ('5', 'Запад'), ('6', 'Область')], default='', max_length=30, verbose_name='Округ'),
        ),
    ]
