# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0004_auto_20170518_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioritet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritet', models.CharField(max_length=30, verbose_name='Приоритет')),
                ('num', models.IntegerField(default=0, verbose_name='Важность')),
            ],
            options={
                'ordering': ['-num'],
                'verbose_name_plural': 'Приоритеты',
                'verbose_name': 'Приоритет',
                'db_table': 'prioritet',
            },
        ),
        migrations.AlterField(
            model_name='taskclient',
            name='prioritet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.Prioritet', verbose_name='Приоритет'),
        ),
    ]
