# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0006_auto_20170525_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritet',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Важность'),
        ),
    ]
