# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0006_auto_20170504_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Okrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=100, verbose_name='Округ')),
            ],
            options={
                'verbose_name_plural': 'Округа',
                'verbose_name': 'Округ',
                'db_table': 'okrug',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='okrug',
        ),
        migrations.AddField(
            model_name='client',
            name='okrug',
            field=models.ManyToManyField(blank=True, to='myclient.Okrug'),
        ),
    ]
