# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0007_auto_20170531_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.Client', verbose_name='Клиент'),
        ),
    ]
