# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0007_auto_20170504_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hide_date',
            field=models.DateField(blank=True, null=True, verbose_name='Скрыть до'),
        ),
        migrations.AlterField(
            model_name='client',
            name='okrug',
            field=models.ManyToManyField(blank=True, to='myclient.Okrug', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_obj',
            field=models.CharField(blank=True, choices=[('undeg', 'Подземка'), ('street', 'Улица'), ('tc', 'Отдел\\ТЦ')], default='undeg', max_length=30, verbose_name='Тип объекта'),
        ),
    ]
