# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import myclient.models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0008_auto_20170620_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskclient',
            name='prioritet',
            field=models.ForeignKey(on_delete=models.SET(myclient.models.TaskClient.prio), to='myclient.Prioritet', verbose_name='Приоритет'),
        ),
    ]
