# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 22:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclient', '0008_auto_20170504_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritet', models.CharField(blank=True, choices=[(0, 'другое'), (1, 'звонок, ответ'), (2, 'первоочередное'), (3, 'встреча, показ')], default='0', max_length=30, verbose_name='Приоритет')),
                ('date', models.DateField(verbose_name='Дата')),
                ('task', models.TextField(verbose_name='Задача')),
            ],
            options={
                'db_table': 'task_client',
                'verbose_name': 'Задача клиента',
                'verbose_name_plural': 'Задачи клиента',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='hide',
            field=models.CharField(blank=True, choices=[('no', 'Не скрыт'), ('yes', 'Скрыт')], default='0', max_length=30, verbose_name='Скрыт'),
        ),
        migrations.AddField(
            model_name='taskclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.Client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='taskclient',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
