# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0009_auto_20170505_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-hide'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='taskclient',
            name='prioritet',
            field=models.CharField(blank=True, choices=[('0', 'другое'), ('1', 'звонок, ответ'), ('2', 'первоочередное'), ('3', 'встреча, показ')], default='0', max_length=30, verbose_name='Приоритет'),
        ),
    ]
