# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0010_auto_20170505_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['hide'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
