# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0010_historicalclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalclient',
            name='change_message',
            field=models.TextField(blank=True, verbose_name='change message'),
        ),
    ]
