# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myclient', '0011_auto_20170506_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_two', models.CharField(max_length=30, verbose_name='Имя')),
                ('bet_name', models.CharField(max_length=128)),
                ('bet_body', models.TextField(blank=True, default=None, null=True)),
                ('bet_end', models.DateField()),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Спор',
                'db_table': 'spor',
                'verbose_name_plural': 'Спор',
            },
        ),
    ]
