# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 23:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myobject.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myclient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeobj', models.CharField(choices=[('1', 'Павильон'), ('2', 'Капитальное'), ('3', 'Отдел\\БЦ\\ТЦ'), ('4', 'Подземка')], default='0', max_length=30, verbose_name='Тип объекта')),
                ('adres', models.CharField(max_length=100, verbose_name='Адрес')),
                ('area', models.IntegerField(default=0, verbose_name='Площадь')),
                ('block_area', models.FloatField(blank=True, default=0, verbose_name='Метраж')),
                ('block_price', models.FloatField(blank=True, default=0, verbose_name='Цена')),
                ('block_procent', models.FloatField(blank=True, default=0, verbose_name='Процент комиссии')),
                ('etaj', models.IntegerField(blank=True, default=0, verbose_name='Этаж')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('opis', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('dom', models.BooleanField(default=False, verbose_name='Дом')),
                ('kvt', models.CharField(blank=True, max_length=50, verbose_name='КВт')),
                ('dogovor', models.CharField(blank=True, max_length=50, verbose_name='Тип договора')),
                ('block_name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('block_tel', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('block_email', models.EmailField(blank=True, max_length=30, verbose_name='Email')),
                ('silka', models.CharField(blank=True, max_length=200, verbose_name='Ссылка на сайт')),
                ('zametka', models.TextField(blank=True, max_length=1000, verbose_name='Заметка')),
                ('hide', models.CharField(blank=True, choices=[('no', 'Нет'), ('yes', 'Все')], default='0', max_length=30, verbose_name='Скрыт')),
                ('hide_date', models.DateField(blank=True, null=True, verbose_name='Скрыть до')),
                ('zvon', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Скрыть до')),
                ('area_range', models.CharField(blank=True, choices=[('small', 'Маленькое до 20 кв.м'), ('middle', 'Среднее от 20 до 80 кв.м'), ('large', 'Большое до 80 кв.м')], max_length=50, null=True)),
                ('my_manager', models.ForeignKey(on_delete=models.SET(myobject.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('naznach', models.ManyToManyField(to='myclient.Naznach', verbose_name='Назначение')),
                ('okrug', models.ManyToManyField(blank=True, to='myclient.Okrug', verbose_name='Округ')),
            ],
            options={
                'ordering': ['hide'],
                'verbose_name_plural': 'Объекты',
                'verbose_name': 'Объект',
                'db_table': 'object',
            },
        ),
        migrations.CreateModel(
            name='StancMetro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет ветки')),
                ('name', models.CharField(max_length=100, verbose_name='Станция')),
                ('okrug', models.ManyToManyField(blank=True, to='myclient.Okrug', verbose_name='Округ')),
            ],
            options={
                'verbose_name_plural': 'Станции метро',
                'verbose_name': 'Стация метро',
                'db_table': 'metro',
            },
        ),
        migrations.AddField(
            model_name='myobject',
            name='station_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_one', to='myobject.StancMetro', verbose_name='Станция метро'),
        ),
        migrations.AddField(
            model_name='myobject',
            name='station_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myobject.StancMetro', verbose_name='Станция метро доп.'),
        ),
    ]
