# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobject',
            name='hide',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('yes', 'Все')], default='0', max_length=30, verbose_name='Скрыт'),
        ),
    ]
