# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0002_auto_20170506_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobject',
            name='naznach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclient.Naznach', verbose_name='Назначение'),
        ),
    ]
