# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-29 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0002_historicalmyobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stancmetro',
            name='color',
            field=models.CharField(choices=[('#b004f0', 'фиолетовая'), ('#ff2915', 'красная'), ('#008d50', 'зелёная'), ('#0073bf', 'синяя'), ('#07e8fc', 'голубая'), ('#5b3119', 'коричневая'), ('#e57d0c', 'оранжевая'), ('#ffe200', 'жёлтая'), ('#8c8082', 'серая'), ('#00fdb5', 'салатовая'), ('#2dbd99', 'бирюзовая'), ('#92c1db', 'серо-голубая')], default='0', max_length=100, verbose_name='Цвет ветки'),
        ),
    ]
