# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myobject.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myobject', '0003_auto_20170629_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.ImageField(upload_to='object_photos/%Y%m')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес')),
                ('my_manager', models.ForeignKey(blank=True, null=True, on_delete=models.SET(myobject.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myobject.MyObject', verbose_name='Объект')),
            ],
        ),
        migrations.AlterModelOptions(
            name='stancmetro',
            options={'ordering': ['id'], 'verbose_name': 'Стация метро', 'verbose_name_plural': 'Станции метро'},
        ),
    ]
