# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myclient', '0013_auto_20170508_2017'),
        ('myobject', '0004_auto_20170509_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myobject',
            name='naznach',
        ),
        migrations.AddField(
            model_name='myobject',
            name='naznach',
            field=models.ManyToManyField(to='myclient.Naznach', verbose_name='Назначение'),
        ),
    ]
