# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0004_auto_20170707_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmyobject',
            name='area_range',
            field=models.CharField(blank=True, choices=[('small', 'Маленькое'), ('middle', 'Среднее'), ('large', 'Большое')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myobject',
            name='area_range',
            field=models.CharField(blank=True, choices=[('small', 'Маленькое'), ('middle', 'Среднее'), ('large', 'Большое')], max_length=50, null=True),
        ),
    ]
