# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0005_auto_20170509_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobject',
            name='my_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
