# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0006_auto_20170509_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobject',
            name='hide',
            field=models.CharField(blank=True, choices=[('no', 'Не скрыт'), ('yes', 'Скрыт')], default='0', max_length=30, verbose_name='Скрыт'),
        ),
        migrations.AddField(
            model_name='myobject',
            name='hide_date',
            field=models.DateField(blank=True, null=True, verbose_name='Скрыть до'),
        ),
    ]
