# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0007_auto_20170510_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myobject',
            options={'ordering': ['hide'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.RenameField(
            model_name='myobject',
            old_name='type_obj',
            new_name='typeobj',
        ),
    ]
