# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myobject', '0008_auto_20170510_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobject',
            name='zvon',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 10, 19, 44, 26, 57366, tzinfo=utc), verbose_name='Скрыть до'),
        ),
    ]
