FROM python:3.4

ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

RUN python -m pip install --upgrade pip

ADD requirements/ /code/requirements/
ADD req.txt /code/

RUN pip install -r req.txt

ADD . /code/
