# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import photo_baza.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myobject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', photo_baza.fields.ThumbnailImageField(upload_to='photo_baza')),
                ('is_main', models.BooleanField(default=False, verbose_name='Заглавная фотография')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myobject.StancMetro', verbose_name='Станция')),
            ],
            options={
                'verbose_name_plural': 'Фото база',
                'verbose_name': 'Фото база',
                'db_table': 'photo_baza',
            },
        ),
    ]
