# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 23:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='ID пользователя')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('tel', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
            options={
                'verbose_name_plural': 'Настройки циан',
                'verbose_name': 'Настройки циан',
                'db_table': 'cian',
            },
        ),
        migrations.CreateModel(
            name='MenagerOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('tel_vlad', models.BooleanField(default=False, verbose_name='Видеть телефон собственика')),
                ('del_obj', models.BooleanField(default=False, verbose_name='Удалять любой объект')),
                ('edit_obj', models.BooleanField(default=False, verbose_name='Редактировать любой объект')),
                ('look', models.BooleanField(default=False, verbose_name='Видит чужих клиентов')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Настроки прав',
                'verbose_name': 'Настроки прав',
                'db_table': 'manager_options',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Meta Title')),
                ('desc', models.TextField(max_length=100, verbose_name='Meta Description')),
                ('keywords', models.TextField(max_length=500, verbose_name='Meta Keywords')),
            ],
            options={
                'verbose_name_plural': 'Настроки сайта\\SEO',
                'verbose_name': 'Настрока сайта\\SEO',
                'db_table': 'seo',
            },
        ),
    ]
