# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='ID пользователя')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('tel', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Настройки циан',
                'db_table': 'cian',
                'verbose_name_plural': 'Настройки циан',
            },
        ),
    ]
